### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by 0x0ece** [terra-money/terra.proto#10]
Can you share what version of python (and poetry) are you using? I'd like to repro your build but it's failing on my system. Thank you

**Comment by Vritra4** [comment]
could you run make again after `pip install MarkupSafe==2.0.1`?
MarkupSafe guys have removed some functions we use. :(

**Comment by Vritra4** [comment]
anyway i'll make a patch to use MarkupSafe==2.0.1. thanks for the report!

**Comment by 0x0ece** [comment]
Cool, it fixed. Just FYI there's another minor issue:
```../terrad/proto: warning: directory does not exist.```
I think this dir got removed from the submodule... but irrelevant to this case.

**Comment by Vritra4** [comment]
yes, `terra/proto` was for classic core. i'll remove that later :)

i'll close this issue anyway. please feel free to reopen it if you want.
