### ISSUE TITLE
Release 1.0.1 deleted

### ISSUE THREAD

**Issue by nerewarin** [terra-money/terra.proto#8]
[This MR](https://github.com/terra-money/terra.proto/commit/af9fdfec09b230b53a24bbfcb560164a252a3fbd#diff-044aba9684085025ca1e21e231413850224aa8b39c5b391d0b87d0c6dc45fbf7) deletes terra_proto/terra folder
which leads to 
ModuleNotFoundError: No module named 'terra_proto.terra'
for 1.0.1 release users.
How to reproduce:
from terra_sdk.core.bech32 import is_acc_address

Suggestion:
recover 1.0.1 tag

**Comment by nerewarin** [comment]
I want to use old core. Could you please just bring back 1.0.1 release?

**Comment by Vritra4** [comment]
closing this issue. please feel free to reopen it if you want.
